--- 
abstract: "Photo vintage filter  "
author: 
  - Naoki Tomita <tomita@cpan.org>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  File::Compare: 0
  File::Temp: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.690
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Imager-Filter-Bakumatsu
no_index: 
  directory: 
    - share
    - inc
    - t
requires: 
  Imager: 0
version: 0.01
